version: '3'

services:
  redis:
    image:
      redis:latest
    ports: 
      - "6739"
    networks:
      - backend
    tty:
      true
    stdin_open:
      true
  server:
    image:
      web-crawler:latest
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - redis
    networks:
      - backend

networks:
  backend:
